# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('dateNaissance', models.DateTimeField()),
                ('sexe', models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], max_length=10)),
                ('profession', models.CharField(max_length=50)),
                ('numTel', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
